icons_format = " <span font_family='FantasqueSansM Nerd Font'>{icon}</span> "

[theme]
theme = "native"

[icons]
icons = "material-nf"

[[block]]
block = "net"
format = "$icon $ssid"

[[block]]
block = "sound"

[[block]]
block = "backlight"

[[block]]
block = "battery"

[[block]]
block = "time"
interval = 5
format = " $timestamp.datetime(f:'%a %d/%m %R', l:pt_BR) "

[[block]]
block = "notify"
driver = "swaync"
format = "$icon {($notification_count.eng(w:1)) |}"
[[block.click]]
button = "left"
action = "show"
[[block.click]]
button = "right"
action = "toggle_paused"
